# Generated by Django 2.2.19 on 2025-06-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplom_spo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplom',
            name='ser_number',
            field=models.CharField(default=True, help_text='введите номер серии', max_length=14, verbose_name='Номер серии'),
        ),
    ]
