# Generated by Django 2.2.19 on 2025-06-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplom_spo', '0002_auto_20250628_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplom',
            name='chairman',
            field=models.CharField(default='Введите данные', help_text='Введите ФИО председатель', max_length=200, verbose_name='Председатель ЭКЗ комиссии'),
        ),
        migrations.AlterField(
            model_name='diplom',
            name='copy',
            field=models.FileField(help_text='Вставьте копию диплома', upload_to='', verbose_name='Копия диплома'),
        ),
        migrations.AlterField(
            model_name='diplom',
            name='grant_date',
            field=models.DateField(default='Введите данные', help_text='Введите дату выдачи', verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='diplom',
            name='org_name',
            field=models.CharField(default='Введите данные', help_text='Введите навзвание образовательной организации', max_length=200, verbose_name='Название образовательной организации'),
        ),
        migrations.AlterField(
            model_name='diplom',
            name='qualification',
            field=models.CharField(default='Введите данные', help_text='Напишите квалификацию', max_length=100, verbose_name='Квалификация'),
        ),
        migrations.AlterField(
            model_name='diplom',
            name='reg_number',
            field=models.CharField(default='Введите данные', help_text='Введите регистрационный номер', max_length=10, verbose_name='Регистрационный номер'),
        ),
        migrations.AlterField(
            model_name='diplom',
            name='ser_number',
            field=models.CharField(default='Введите данные', help_text='Введите номер серии', max_length=100, verbose_name='Номер серии'),
        ),
        migrations.AlterField(
            model_name='diplom',
            name='speciality',
            field=models.CharField(default='Введите данные', help_text='Введите специальность', max_length=100, verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='diplom',
            name='student_name',
            field=models.CharField(default='Введите данные', help_text='ФИО', max_length=200, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='diplom',
            name='supervisor',
            field=models.CharField(default='Введите данные', help_text='Введите ФИО руководителя', max_length=200, verbose_name='Руководитель'),
        ),
        migrations.AlterField(
            model_name='diplom',
            name='year',
            field=models.DateField(default='Введите данные', help_text='Введите дату решения', verbose_name='Дата решения'),
        ),
    ]
