# Generated by Django 2.2.19 on 2025-06-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplom_spo', '0003_auto_20250628_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplom',
            name='grant_date',
            field=models.DateField(help_text='Введите дату выдачи', verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='diplom',
            name='year',
            field=models.DateField(help_text='Введите дату решения', verbose_name='Дата решения'),
        ),
    ]
