# Generated by Django 2.2.19 on 2025-06-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplom_spo', '0004_auto_20250628_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplom',
            name='copy',
            field=models.ImageField(help_text='Вставьте копию диплома', upload_to='', verbose_name='Копия диплома'),
        ),
    ]
