# Generated by Django 2.2.19 on 2025-07-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplom_spo', '0007_auto_20250701_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplom',
            name='copy',
            field=models.ImageField(help_text='Вставьте копию диплома', upload_to='', verbose_name='Копия диплома'),
        ),
    ]
