# Generated by Django 2.2.19 on 2025-07-01 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diplom_spo', '0008_auto_20250701_1245'),
        ('diplom_spo', '0006_auto_20250701_1244'),
    ]

    operations = [
    ]
