# Generated by Django 2.2.19 on 2025-07-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplom_spo', '0009_merge_20250701_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplom',
            name='copy',
            field=models.ImageField(blank=True, help_text='Вставьте копию диплома', null=True, upload_to='', verbose_name='Копия диплома'),
        ),
    ]
